
spring:
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: optional:configserver:http://localhost:8888/config
  profiles:
    active: sms, letter
  zipkin:
    base-url: http://localhost:9411
  main:
    allow-circular-references: true