spring:
  application:
    name: DISCOVERY-SERVICE

server:
  port: 8761

eureka:
  instance:
    hostname: 172.18.0.3
    prefer-ip-address: true
  client:
    #essendo eureka server non ho bisogno di registrarmi come client
    register-with-eureka: false
    fetch-registry: false
