spring:
  application:
    name: PIZZA-SERVICE
  config:
    import: optional:configserver:http://host.docker.internal:8888/config
  profiles:
    active: default
    #se inserisco il profilo prod allora il configService gli passa il file con il nome-{nome profilo}
    #active: prod
  zipkin:
    base-url: http://zipkin:9411
  main:
    allow-circular-references: true