spring:
  application:
    name: PIZZA-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2_pizza_service?useSSL=false
    username: gian
    password: Gianluca
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  port: 8081
  servlet:
    context-path: /api
