
spring:
  application:
    name: RESTAURANT-SERVICE
  config:
    import: optional:configserver:http://host.docker.internal:8888/config
  profiles:
    active: prod
  zipkin:
    base-url: http://zipkin:9411
  main:
    allow-circular-references: true






#Configurazione MySql

#spring:
#  application:
#    name: RESTAURANT-SERVICE
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db2_restaurant_service?useSSL=false
#    username: gian
#    password: Gianluca
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#
#  mvc:
#    path match:
#      matching-strategy: ant_path_matcher
#
#server:
#  port: 8082
#  servlet:
#    context-path: /api
#



# configurazione H2
#spring:
#  application:
#    name: RESTAURANT-SERVICE
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/data/RestaurantServiceDB;AUTO_SERVER=TRUE
#    username: sa
#    password: sa
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#
#server:
#  port: 8082
#  servlet:
#    context-path: /api