spring:
  application:
    name: DISCOVERY-SERVICE

server:
  port: 8761

eureka:
  client:
    #essendo eureka server non ho bisogno di registrarmi come client
    register-with-eureka: false
    fetch-registry: false
